Move download recalculations to after payment actions hook
awesomemotive/easy-digital-downloads pull request #9403
Opened 2022-08-31 01:08 UTC by robincornett

Proposed Changes:
1. Instead of recalculating download sales and earnings on the Berlin transition hooks, use the `edd_after_payment_actions` hook to have the recalculations run outside of the actual purchase transaction.

2022-08-31 18:27 UTC, cklosowski requested changes
Just some variable name changes to make it more clear what we're passing around, IDs instead of full order item objects.

2022-08-31 18:27 UTC, cklosowski commented on includes/orders/functions/transitions.php
> +	foreach ( $order_items as $order_item ) {
```suggestion
	foreach ( $order_item_product_ids as $product_id ) {
```

2022-08-31 18:27 UTC, cklosowski commented on includes/orders/functions/transitions.php
> +		edd_recalculate_download_sales_earnings( $order_item );
```suggestion
		edd_recalculate_download_sales_earnings( $product_id );
```

2022-08-31 18:27 UTC, cklosowski commented on includes/orders/functions/transitions.php
> +	$order_items = edd_get_order_items(
```suggestion
	$order_item_product_ids = edd_get_order_items(
```

2022-08-31 19:07 UTC, cklosowski commented
@robincornett while testing this I noticed the download stats were actually updated much earlier than the cron was running and I think it's due to the `EDD_Payment` class running this:
```
		$order_items = edd_get_order_items( array(
			'order_id' => $this->ID,
			'fields'   => 'product_id',
		) );
		foreach ( $order_items as $item_id ) {
			edd_recalculate_download_sales_earnings( $item_id );
		}
```

This is being run when gateways like Stripe call `$payment->save()`.

2022-09-01 19:04 UTC, robincornett commented
Closing this PR as I want to try a different approach.

2022-09-01 19:04 UTC, closed without merging