Restrict the ajax downloads search to titles only
awesomemotive/easy-digital-downloads pull request #9509
Opened 2022-10-13 22:31 UTC by robincornett

Fixes #9508

Proposed Changes:
1. Adds a filter on the `WHERE` clause for the ajax downloads search. This restricts the search to run on the download titles only, instead of including the content and excerpt.

2022-10-14 16:27 UTC, cklosowski requested changes

2022-10-14 16:27 UTC, cklosowski commented on includes/ajax-functions.php
> +	$search = $wp_query->get( 'edd_search' );
We should be use `esc_like` to do proper sanitization of the search query before using it.
https://developer.wordpress.org/reference/classes/wpdb/esc_like/

2022-10-14 21:58 UTC, cklosowski commented
This I believe is unrelated as I can produce it on `release/3.1.0.2`, but the `(All Price Options)` is being added to all items after searching, pushed up a change to address that while we're in here making changes.

Initial Page load and opening the chosen box, A Music Album is showing the All option as well as every price option.
![image](https://user-images.githubusercontent.com/1390124/195949469-928dd4f9-435c-4e23-8c96-ccdb0117a3d3.png)

Once searching I end up with all the options still but they have '(All Options)' added to them:
![image](https://user-images.githubusercontent.com/1390124/195949563-061baa57-1b63-423a-8152-89c040b254ff.png)

2022-10-17 11:38 UTC, robincornett commented
Just noting that I see the issue you've flagged @cklosowski and agree with your fix.

2022-10-17 13:29 UTC, cklosowski approved these changes

2022-10-17 13:39 UTC, merged